In [ ]:
#!gunzip -k 'daily_dataset.csv.gz'

In [ ]:
import pandas as pd
import numpy as np
from pandas import datetime
import os
import math
from matplotlib import pyplot as plt
%matplotlib inline
import seaborn as sns
import calendar
sns.set(color_codes=True)

In [ ]:
daily = pd.read_csv('daily_dataset.csv')
daily.head()

,LCLid,day,energy_median,energy_mean,energy_max,energy_count,energy_std,energy_sum,energy_min
0,MAC000131,2011-12-15,0.4850,0.432045,0.868,22,0.239146,9.505,0.072
1,MAC000131,2011-12-16,0.1415,0.296167,1.116,48,0.281471,14.216,0.031
2,MAC000131,2011-12-17,0.1015,0.189812,0.685,48,0.188405,9.111,0.064
3,MAC000131,2011-12-18,0.1140,0.218979,0.676,48,0.202919,10.511,0.065
4,MAC000131,2011-12-19,0.1910,0.325979,0.788,48,0.259205,15.647,0.066

In [ ]:
daily.columns

Index(['LCLid', 'day', 'energy_median', 'energy_mean', 'energy_max',
       'energy_count', 'energy_std', 'energy_sum', 'energy_min'],
      dtype='object')

In [ ]:
daily.day.value_counts()

2012-12-18    5541
2012-11-20    5532
2012-11-21    5532
2012-11-19    5532
2012-11-17    5531
              ...
2011-11-27      41
2011-11-26      41
2011-11-25      32
2011-11-24      25
2011-11-23      13
Name: day, Length: 829, dtype: int64

In [ ]:
acorn = pd.read_csv('informations_households.csv')
acorn.head()

       LCLid stdorToU    Acorn Acorn_grouped     file
0  MAC005492      ToU   ACORN-        ACORN-  block_0
1  MAC001074      ToU   ACORN-        ACORN-  block_0
2  MAC000002      Std  ACORN-A      Affluent  block_0
3  MAC003613      Std  ACORN-A      Affluent  block_0
4  MAC003597      Std  ACORN-A      Affluent  block_0

In [ ]:
daily_acorn = pd.merge(daily[['LCLid', 'day','energy_sum']],acorn[['LCLid','Acorn']], on='LCLid')#,how='left')

In [ ]:
daily_acorn.head()

       LCLid         day  energy_sum    Acorn
0  MAC000131  2011-12-15       9.505  ACORN-E
1  MAC000131  2011-12-16      14.216  ACORN-E
2  MAC000131  2011-12-17       9.111  ACORN-E
3  MAC000131  2011-12-18      10.511  ACORN-E
4  MAC000131  2011-12-19      15.647  ACORN-E

In [ ]:
daily_acorn.day.value_counts()

2012-12-18    5541
2012-11-20    5532
2012-11-21    5532
2012-11-19    5532
2012-11-17    5531
              ...
2011-11-27      41
2011-11-26      41
2011-11-25      32
2011-11-24      25
2011-11-23      13
Name: day, Length: 829, dtype: int64

In [ ]:
daily_acorn[daily_acorn.LCLid == 'MAC005556']

,LCLid,day,energy_median,energy_mean,energy_max,energy_count,energy_std,energy_sum,energy_min,Acorn
1223192,MAC005556,2012-12-19,NaN,NaN,NaN,0,NaN,NaN,NaN,ACORN-Q

In [ ]:
#daily_acorn.day.apply(lambda x: datetime.strptime(x, '%Y-%m-%d'))

In [ ]:
daily_acorn['date'] = pd.to_datetime(daily_acorn['day'])

In [ ]:
daily_acorn['day_of_week'] = daily_acorn['date'].apply(lambda x: x.weekday()) # get the weekday index, between 0 and 6
daily_acorn['day_of_week'] = daily_acorn['day_of_week'].apply(lambda x: calendar.day_name[x])
daily_acorn.head()

       LCLid         day  energy_sum    Acorn       date day_of_week
0  MAC000131  2011-12-15       9.505  ACORN-E 2011-12-15    Thursday
1  MAC000131  2011-12-16      14.216  ACORN-E 2011-12-16      Friday
2  MAC000131  2011-12-17       9.111  ACORN-E 2011-12-17    Saturday
3  MAC000131  2011-12-18      10.511  ACORN-E 2011-12-18      Sunday
4  MAC000131  2011-12-19      15.647  ACORN-E 2011-12-19      Monday

In [ ]:
daily_acorn['weekend']= pd.Series(np.where((daily_acorn.day_of_week.values == 'Saturday') | (daily_acorn.day_of_week.values == 'Sunday'), 1, 0),daily_acorn.index)
daily_acorn.head()

       LCLid         day  energy_sum    Acorn       date day_of_week  weekend
0  MAC000131  2011-12-15       9.505  ACORN-E 2011-12-15    Thursday        0
1  MAC000131  2011-12-16      14.216  ACORN-E 2011-12-16      Friday        0
2  MAC000131  2011-12-17       9.111  ACORN-E 2011-12-17    Saturday        1
3  MAC000131  2011-12-18      10.511  ACORN-E 2011-12-18      Sunday        1
4  MAC000131  2011-12-19      15.647  ACORN-E 2011-12-19      Monday        0

In [ ]:
daily_acorn.day.value_counts()

2012-12-18    5541
2012-11-20    5532
2012-11-21    5532
2012-11-19    5532
2012-11-17    5531
              ...
2011-11-27      41
2011-11-26      41
2011-11-25      32
2011-11-24      25
2011-11-23      13
Name: day, Length: 829, dtype: int64

In [ ]:
holidays_df=pd.read_csv("UK Bank Holidays.csv")
print(holidays_df.shape)
holidays_df.head()

(385, 3)

                               Name  Bank Holiday        Date
0                    New Year's Day             1  2009-01-01
1  Robert Burns Night (Burns Night)             0  2009-01-25
2            Holocaust Memorial Day             0  2009-01-27
3                    Valentines Day             0  2009-02-14
4      Shrove Tuesday (Pancake Day)             0  2009-02-24

In [ ]:
holidays_df=holidays_df[holidays_df['Bank Holiday']==1].reset_index(drop=True)
holidays_df.head()

                               Name  Bank Holiday        Date
0                    New Year's Day             1  2009-01-01
1                       Good Friday             1  2009-04-10
2                     Easter Monday             1  2009-04-13
3  May Day (Early May Bank Holiday)             1  2009-05-04
4               Spring Bank Holiday             1  2009-05-25

In [ ]:
holidays=holidays_df['Date']
daily_acorn['Holiday'] = daily_acorn['day'].isin(holidays)
daily_acorn['Holiday'] =daily_acorn['Holiday'].astype(int)
daily_acorn.sample(20)

,LCLid,day,energy_sum,Acorn,date,day_of_week,weekend,Holiday
619593,MAC003746,2013-11-19,65.265,ACORN-E,2013-11-19,Tuesday,0,0
1254620,MAC005330,2012-10-14,10.262,ACORN-H,2012-10-14,Sunday,1,0
2866095,MAC001582,2012-06-20,3.430,ACORN-Q,2012-06-20,Wednesday,0,0
3078448,MAC001206,2013-04-30,5.181,ACORN-E,2013-04-30,Tuesday,0,0
1357910,MAC000030,2011-12-22,7.917,ACORN-A,2011-12-22,Thursday,0,0
2443204,MAC000032,2012-02-26,15.278,ACORN-Q,2012-02-26,Sunday,1,0
1148286,MAC002637,2012-05-09,11.291,ACORN-K,2012-05-09,Wednesday,0,0
678823,MAC000058,2012-01-26,3.173,ACORN-E,2012-01-26,Thursday,0,0
535550,MAC004858,2013-01-02,38.283,ACORN-E,2013-01-02,Wednesday,0,0
3478278,MAC000078,2012-09-16,2.403,ACORN-E,2012-09-16,Sunday,1,0
434134,MAC003574,2013-09-15,20.103,ACORN-L,2013-09-15,Sunday,1,0
2204889,MAC001624,2013-10-18,2.978,ACORN-E,2013-10-18,Friday,0,0
3418529,MAC000581,2012-08-22,7.081,ACORN-N,2012-08-22,Wednesday,0,0
864704,MAC005440,2013-03-28,11.982,ACORN-E,2013-03-28,Thursday,0,0
3315037,MAC004984,2012-12-18,15.299,ACORN-E,2012-12-18,Tuesday,0,0
1171459,MAC002908,2013-08-16,6.085,ACORN-H,2013-08-16,Friday,0,0
1613902,MAC002437,2012-08-26,8.707,ACORN-H,2012-08-26,Sunday,1,0
2899956,MAC001576,2013-07-12,23.851,ACORN-E,2013-07-12,Friday,0,0
2846437,MAC004512,2012-01-05,8.476,ACORN-E,2012-01-05,Thursday,0,0
3196672,MAC000432,2013-01-11,6.394,ACORN-F,2013-01-11,Friday,0,0

In [ ]:
daily_acorn['month'] = daily_acorn.date.dt.month
daily_acorn['year'] = daily_acorn.date.dt.year

In [ ]:
sp = list(np.where((daily_acorn.month.values == 3) | (daily_acorn.month.values == 4) | (daily_acorn.month.values == 5))[0])
su = list(np.where((daily_acorn.month.values == 6) | (daily_acorn.month.values == 7) | (daily_acorn.month.values == 8))[0])
au = list(np.where((daily_acorn.month.values == 9) | (daily_acorn.month.values == 10) | (daily_acorn.month.values == 11))[0])
wi = list(np.where((daily_acorn.month.values == 12) | (daily_acorn.month.values == 1) | (daily_acorn.month.values == 2))[0])

In [ ]:
daily_acorn['season'] = ''
daily_acorn.loc[sp, 'season'] = 'Spring'
daily_acorn.loc[su, 'season'] = 'Summer'
daily_acorn.loc[au, 'season'] = 'Autumn'
daily_acorn.loc[wi, 'season'] = 'Winter'

In [ ]:
daily_acorn=daily_acorn.drop(['date'],axis=1)

In [ ]:
daily_acorn.head()

,LCLid,day,energy_sum,Acorn,day_of_week,weekend,Holiday,month,year,season
0,MAC000131,2011-12-15,9.505,ACORN-E,Thursday,0,0,12,2011,Winter
1,MAC000131,2011-12-16,14.216,ACORN-E,Friday,0,0,12,2011,Winter
2,MAC000131,2011-12-17,9.111,ACORN-E,Saturday,1,0,12,2011,Winter
3,MAC000131,2011-12-18,10.511,ACORN-E,Sunday,1,0,12,2011,Winter
4,MAC000131,2011-12-19,15.647,ACORN-E,Monday,0,0,12,2011,Winter

In [ ]:
daily_acorn.day.value_counts()

2012-12-18    5541
2012-11-20    5532
2012-11-21    5532
2012-11-19    5532
2012-11-17    5531
              ...
2011-11-27      41
2011-11-26      41
2011-11-25      32
2011-11-24      25
2011-11-23      13
Name: day, Length: 829, dtype: int64

In [ ]:
daily_acorn.to_csv('final_daily_dataset.csv', index=False)